# هذا هو ملف الإعدادات الرئيسي لـ Netlify CMS.
# يحدد هذا الملف كيفية تنظيم المحتوى الخاص بك في لوحة تحكم Netlify CMS،
# وأنواع المحتوى التي يمكنك إدارتها، والحقول المتاحة لكل نوع.

backend:
  name: git-gateway # يستخدم Git Gateway لربط Netlify CMS بمستودع Git الخاص بك
  branch: main # الفرع الرئيسي لمستودع Git الخاص بك

local_backend: true # لتمكين التشغيل المحلي لـ Netlify CMS (للتطوير)

media_folder: "assets/images" # المجلد الذي يتم فيه تخزين الصور والملفات المرفوعة
public_folder: "/assets/images" # المسار العام للصور والملفات المرفوعة

collections:
  - name: "posts" # اسم المجموعة (يمكن أن يكون "services" بدلاً من "posts" إذا كنت تفضل)
    label: "الخدمات" # العنوان الذي يظهر في واجهة المستخدم
    folder: "_data" # المجلد الذي سيتم تخزين بيانات هذه المجموعة فيه (مثال: _data/posts.json)
    create: true # السماح بإنشاء عناصر جديدة في هذه المجموعة
    slug: "{{slug}}" # يستخدم اسم الملف كـ slug
    identifier_field: "title" # يحدد الحقل الذي سيستخدم كمعرف فريد
    extension: "json" # امتداد الملفات لهذه المجموعة
    format: "json" # تنسيق الملفات (JSON في هذه الحالة)
    fields:
      - {label: "العنوان", name: "title", widget: "string"}
      - {label: "الوصف", name: "description", widget: "text"}
      # يمكنك إضافة المزيد من الحقول هنا حسب حاجتك لكل خدمة
      # - {label: "صورة", name: "image", widget: "image", required: false}
      # - {label: "الترتيب", name: "order", widget: "number", required: false}
  
  - name: "site_settings" # اسم المجموعة لإعدادات الموقع العامة
    label: "إعدادات الموقع"
    files:
      - file: "_data/tokens.json" # المسار إلى ملف إعدادات الموقع
        label: "البيانات الأساسية"
        name: "tokens"
        fields:
          - {label: "اسم الموقع", name: "site_name", widget: "string"}
          - {label: "وصف الموقع", name: "site_description", widget: "text"}
          - {label: "رابط الموقع", name: "site_url", widget: "string"}
          - {label: "رقم الهاتف", name: "phone_number", widget: "string"}
          - {label: "رقم الواتساب", name: "whatsapp_number", widget: "string"}
          - {label: "البريد الإلكتروني (اختياري)", name: "email_address", widget: "string", required: false}
          - {label: "سنة حقوق النشر", name: "copyright_year", widget: "string", default: "2024"}
          - label: "روابط التواصل الاجتماعي"
            name: "social_links"
            widget: "object"
            fields:
              - {label: "تويتر", name: "twitter", widget: "string", required: false}
              - {label: "فيسبوك", name: "facebook", widget: "string", required: false}
              - {label: "انستغرام", name: "instagram", widget: "string", required: false}
      - file: "_data/site.json" # المسار إلى ملف البيانات الإضافية للموقع
        label: "بيانات إضافية للموقع"
        name: "site_data"
        fields:
          - {label: "سنة التأسيس", name: "establishment_year", widget: "string", required: false}
          - {label: "منطقة الخدمة الرئيسية", name: "main_service_area", widget: "string", required: false}
          - {label: "رمز العملة", name: "currency_code", widget: "string", required: false}
          - label: "ساعات الاتصال"
            name: "contact_hours"
            widget: "object"
            fields:
              - {label: "بداية", name: "start", widget: "string", required: false}
              - {label: "نهاية", name: "end", widget: "string", required: false}
              - {label: "ملاحظات", name: "notes", widget: "string", required: false}

  - name: "pages" # لإدارة الصفحات الثابتة مثل "سياسة الخصوصية" و"شروط الاستخدام"
    label: "الصفحات"
    folder: "src/pages" # المجلد الذي يحتوي على صفحاتك
    create: true
    slug: "{{slug}}"
    extension: "md" # يمكن أن تكون markdown أو njk
    fields:
      - {label: "العنوان", name: "title", widget: "string"}
      - {label: "الوصف", name: "description", widget: "string", required: false}
      - {label: "التخطيط", name: "layout", widget: "hidden", default: "layouts/page.njk"} # استخدام تخطيط الصفحة
      - {label: "رابط URL", name: "permalink", widget: "string", required: false} # يمكن تحديد رابط مخصص
      - {label: "المحتوى", name: "body", widget: "markdown"}

  - name: "navigation" # لإدارة روابط التنقل
    label: "التنقل"
    files:
      - file: "_data/navigation.json" # المسار إلى ملف التنقل
        label: "روابط التنقل الرئيسية"
        name: "main_nav"
        fields:
          - label: "عناصر التنقل"
            name: "items"
            widget: "list"
            fields:
              - {label: "نص الرابط", name: "text", widget: "string"}
              - {label: "رابط URL", name: "url", widget: "string"}

